# Generated by Django 5.1.5 on 2025-01-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'Оплачено'), (2, 'Готово'), (3, 'В ожидании')], default=3),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__gte', 3), ('status__lte', 1)), name='Allowable status values', violation_error_message='Кодовый номер статуса не может быть меньше 1 или больше 3'),
        ),
    ]
