# Generated by Django 5.1.5 on 2025-01-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status_order_allowable_status_values'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='Allowable status values',
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__gte', 1), ('status__lte', 3)), name='Allowable status values', violation_error_message='Кодовый номер статуса не может быть меньше 1 или больше 3'),
        ),
    ]
